language: python
python:
  - 2.7
install:
  - python setup.py install
  - pip install coverage
  - pip install codecov
  - pip install pytest
script: coverage run setup.py test
after_success:
- codecov
